name: .NET

on: 
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build solution and generate NuGet package
      run: dotnet pack -c Release -o out -p:PackageVersion=${GITHUB_REF##*/}
      working-directory: SpeckleCore

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./*.nupkg --skip-duplicate --api-key ${{ secrets.SPECKLE_NUGET_AUTH_TOKEN }} --source https://api.nuget.org/v3/index.json
      working-directory: SpeckleCore/out


    
